import Head from 'next/head'
import React from "react"
import styles from '../styles/Home.module.css'
import File from "../static/pendo"

export default function Home() {
  const [show, setShow] = React.useState(true);
 var res = ""
    setTimeout(()=>{
      res = "1234";
    },1000)
    async function setAuth() {
      var get = await res;
      if(typeof window !== undefined){
        window.pendo.initialize({
          visitor: {
            id: '123466'   // Required if user is logged in
            // email:        // Recommended if using Pendo Feedback, or NPS Email
            // full_name:    // Recommended if using Pendo Feedback
            // role:         // Optional
  
            // You can add any additional visitor level key-values here,
            // as long as it's not one of the above reserved names.
          },
  
          account: {
            id: '1233466' // Required if using Pendo Feedback
            // name:         // Optional
            // is_paying:    // Recommended if using Pendo Feedback
            // monthly_value:// Recommended if using Pendo Feedback
            // planLevel:    // Optional
            // planPrice:    // Optional
            // creationDate: // Optional
  
            // You can add any additional account level key-values here,
            // as long as it's not one of the above reserved names.
          }
        });   
        console.log("completed")
      }
     
    }

    // const pendoFeedback = () =>{
    //   if(typeof window != "undefined"){
    //     if(window.pendo.guides && window.pendo.guides[0]?.isShown()){
    //       window.pendo.guides[0].hide();
    //     }else{
    //       window.pendo.guides[0].show()
    //     }
    //   }
    // }

    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <script type="text/javascript" src={File}></script>
        </Head>


        <button onClick={setAuth}>setAuth</button>
        <button style={{    position: "absolute",
    bottom: 10,
    right: 30,
    padding: 10,
    borderRadius: 100,
    background: "red",
    color: "white"}} >o</button>

    {
      show ? <button style={{    position: "absolute",
      bottom: 10,
      right: 30,
      padding: 10,
      borderRadius: 100,
      background: "red",
      color: "white"}} onClick={()=>setShow(!show)}>o</button>:<button style={{    position: "absolute",
      bottom: 10,
      right: 30,
      padding: 10,
      borderRadius: 100,
      background: "red",
      color: "white"}} onClick={()=>{
        if(typeof document != undefined){
          const doc = document.querySelector("#pendo-close-guide-a8014f57");
          const doc1 = document.querySelector("#pendo-close-guide-365bd065");
          if(doc){
            doc.click();
          }
          if(doc1){
            doc1.click();
          }
        }
        setShow(!show)
      }}>x</button>
    }

      </div>
    )
  

}
